title: "Harrison Haas"
description: "A site built with Jekyll on GitHub Pages"
theme: minima

markdown: kramdown
highlighter: rouge

url: "https://Harrison-Haas.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
  - index.md
